- cmake/modules/PyTypeUtils.cmake
- pytype/analyze.py
- pytype/io.py
- pytype/tools/xref/main.py
- pytype/typegraph/cfg.cc
Pulling in Siva's reference leak fixes to see if they resolve our test issues.
> Google sync

- pytype/__version__.py
> Internal copy of https://github.com/google/pytype/pull/124.

- build_scripts/run_tests.py
> Adjust run_tests.py to reflect the fact that it also runs C++ unit tests.

- pytype/tools/xref/indexer.py
- pytype/tools/xref/kythe.py
- pytype/tools/xref/output.py
> Refactor: Move the kythe graph generation into its own file.

- pytype/pytd/parse/preconditions.py
Import of GitHub PR #142: Future-proof preconditions.py:_TOKEN_RE
Resolves #142
PiperOrigin-RevId: 211523402
> Future-proof preconditions.py:_TOKEN_RE

- .travis.yml
- build_scripts/build_utils.py
- build_scripts/travis_script.py
Three steps have been added to build, test and type check pytype sources.
> Organize Travis commands into steps.

- setup.py
Also upgrade development status to stable.
> Add a dependency on typed_ast

- .travis.yml
- pylintrc
I write pylintrc.
The purpose of the pylintrc is to disable vanilla pylint error.
If my pylintrc is against the Google linter, please let me know.
> Add pylintrc #278

- setup.py
Bumps the version to pull in the fix for https://github.com/google/pytype/issues/318.
> Bump the required importlab version.

- build_scripts/test_module.py
pytype/tools/merge_pyi/test_merge_pyi.py uses the load_tests
protocol, and I'd like to be able to run this test
externally because I'm making some changes to merge-pyi.
> Support the load_tests protocol in build_scripts.test_module.

- 2.7_patches/lib2to3_Grammar_txt.diff
- setup.py
* Creates a patch of our local edits.
* Puts the grammar file in setup.py data.
Fixes https://github.com/google/pytype/issues/332.
> Finish adding merge-pyi's local copy of the lib2to3 grammar.

- README.md
You can install pytype if you use WSL on windows.
> add WSL directions

- README.md
- docs/index.md
Add link to LICENSE file
Resolves #433
PiperOrigin-RevId: 274914616
> Update README.md (#433)

- pytype/metrics.py
- pytype/pytd/parse/node.py
This PR fixed and seems to be close #466.
Resolves #471
PiperOrigin-RevId: 284834257
> Fixed AttributeError in Python 3.8 (#466) (#471)

- setup.py
Fixes https://github.com/google/pytype/issues/239.
> Fix broken links in pytype's PyPI description.

- CHANGELOG
- pytype/__version__.py
> Update pytype CHANGELOG and __version__ for PyPI release.

- CHANGELOG
- pytype/__version__.py
> Do another PyPI release for a typeshed bug fix.

- pytype/tests/test_import.py
External copy of internal typeshed update.
> Update typeshed to d5851eca6f448b648e1a7b3f3010cc3dde498535.

- CHANGELOG
- pytype/__version__.py
> Do a PyPI release of the implicit Optional change.

- .travis.yml
- build_scripts/run_tests.py
- build_scripts/travis_script.py
- cmake/modules/PyTypeUtils.cmake
- setup.cfg
For https://github.com/google/pytype/issues/545.
> Drop host Python 2 support.

- .travis.yml
- pytype/pyi/parser_test.py
- pytype/tools/traces/visitor_test.py
- pytype/typegraph/cfg.cc
- setup.cfg
The unusual testing setup makes this very hard to test locally, but this PR is an attempt to get an idea of what exactly needs to be done to support Python 3.8+ in pytype.
> Initial stab at Python 3.8 support

- build_scripts/travis_script.py
At least locally, this makes the pytype run a lot faster.
> Add --jobs=auto to the travis script's pytype run.

- .travis.yml
- requirements.txt
For https://github.com/google/pytype/issues/642.
> Switch fully to pip installing ninja.

- CHANGELOG
- pytype/__version__.py
> Do a PyPI release.

- pytype/tools/analyze_project/main.py
This PR automatically creates a .gitignore file to the output directory of pytype/tools/analyze_project/main.py
Resolves #770
PiperOrigin-RevId: 348859523
> Automatically added git ignore file to sub directory (#770)

- requirements.txt
- setup.cfg
Resolves https://github.com/google/pytype/issues/794.
> Bump required importlab version to pick up a bug fix.

- requirements.txt
- setup.cfg
For https://github.com/google/pytype/issues/820.
> Add toml as a dependency.

- CHANGELOG
- pytype/__version__.py
> Prepare a PyPI release.

- CHANGELOG
- pytype/__version__.py
> Prepare a 2021-04-01 PyPI release (not a joke, really!).

- requirements.txt
- setup.cfg
For https://github.com/google/pytype/issues/909.
> Pin attrs to 20.3.0.

- requirements.txt
- setup.cfg
See https://github.com/google/pytype/issues/909.
> Require attrs>=21.2.0.

- pytype/tests/test_utils.py
> Removed sorted() call since we're on py3

- .gitmodules
I followed https://gist.github.com/myusuf3/7f645819ded92bda6677.
> Delete no-longer-needed cpython submodule.

- requirements.txt
- setup.cfg
> remove no-longer-needed dependencies

- .github/workflows/build.yml
- build_scripts/wheels/manylinux.sh
Added linux aarch64 wheel build support.
Related to https://github.com/google/pytype/issues/1037, @rchen152 Could you please review this PR?
> Add Linux AArch64 wheel build support

- .github/workflows/ci.yml
- requirements.txt
Resolves https://github.com/google/pytype/issues/1047.
> Remove typed-ast version hack.

- .github/workflows/build.yml
- .github/workflows/ci.yml
- setup.cfg
Closes https://github.com/google/pytype/issues/1022.
Closes https://github.com/google/pytype/pull/1118.
> Enable Python 3.10.

- pytype/abstract/class_mixin.py
- pytype/tests/test_dataclasses.py
In subclasses of a Generic dataclass, the init method accepts the right argument count, instead of expecting the argument number from it parent's init method and raising a wrong-arg-count error.
Also add support for checking parameterized types of dataclass and raising wrong-arg-types.
Fixes #1104
Resolves #1218
PiperOrigin-RevId: 453595104
> Fix parameterized attributes for dataclass subclasses (#1218)

- .github/workflows/build.yml
- .github/workflows/ci.yml
* https://github.com/actions/checkout/releases
* https://github.com/actions/setup-python/releases
* https://github.com/actions/upload-artifact/releases
* https://github.com/docker/setup-qemu-action/releases
* https://github.com/styfle/cancel-workflow-action/releases
> Upgrade GitHub Actions

- requirements.txt
- setup.cfg
Removed unused data classes and typed_ast also modified versions.
> modified requirements.txt by removing unused stuff

- requirements.txt
- setup.cfg
> Bump importlab version to pick up an import resolution fix.
