google/pytype

.gitmodules
The former version had a problem with our proxy.
=> Use an official Github URL in .gitmodules

setup.py
This fixes the install problem that prevents pytype to install in the typeshed tests, as reported here:
https://travis-ci.org/python/typeshed/jobs/200196205
=> typeshed/stdlib/2.7 has been moved to .../2.

.travis.yml
This is required so that Travis' virutalenvs can setup the include directory
correctly. Pytype's extension modules can then be built pointing to the
header files corresponding to the correct Python version.
=> Install python3.5-dev and python3.6-dev.

build_scripts/build.py, build_scripts/build_utils.py, build_scripts/run_tests.py
Specifying this option builds all Pytype targets in the debug mode. It is useful, for example, to enable C++ logging.
=> Add --debug option to the scripts build.py and run_tests.py

CONTRIBUTING.md
Import of GitHub PR #67: Fix repeated "the" in CONTRIBUTING.md
https://github.com/google/pytype/pull/67
Resolves #67
Last section ("The small print") has a repeated "the":
> they're covered by the the Software Grant
This commit fixes that.
Merge 57aead5d81540479dd598fd261029e216fe343d8 into 5fbe24a055fa22e973d946479e3e71ec0c4be086
PiperOrigin-RevId: 207619395
=> Fix repeated "the" in CONTRIBUTING.md

pytype/config.py
When pytype is called from analyze_project, we need to be able to...
Resolves #117
PiperOrigin-RevId: 208110379
=> Allow pytype to override an existing logging level. (#117)

2.7_patches/python_2_7_type_annotations.diff
It can now be applied cleanly to CPython 2.7 HEAD.
Tested by applying the patch on the current 2.7 HEAD and getting a clean
run of the CPython test suite.
=> Update the type annotations backporting patch.

pytype/tools/analyze_project/main.py, pytype/tools/analyze_project/parse_args.py, pytype/tools/analyze_project/parse_args_test.py
* Supports an --exclude flag to make it easy to exclude parts of
a directory that are not pytype-safe (e.g.,
`pytype subpackage --exclude subpackage/*_test.py`)
* Renames the filenames arg to inputs in preparation for adding
it to the configuration file, since `filenames` is a bit of a
misnomer when we allow directories as well.
This PR will have to be imported into Google and then re-exported.
=> Support excluding files or directories from analyze_project.

build_scripts/run_cc_test.py
This script will be called from the CMake cc_test rule.
[Changes to the rule to make use of this script will be made as a
Google internal change and exported to Github.]
=> Add a simple script to run a C++ unit test binary.

.gitmodules, build_scripts/build.py, build_scripts/build_utils.py, build_scripts/py27.py
Extended the build script to build the patched Python2.7 interpreter if
the option "--py27" is specified. A standalone script which can build
the patched interpreter has also been added. This script will be used by
a CMake target to build the patched interpreter as part of the
run_tests.py flow.
=> Add cpython submodule pinned to the current 2.7 HEAD.

CHANGELOG, pytype/tools/analyze_project/pytype_runner.py, pytype/tools/analyze_project/pytype_runner_test.py, setup.py
Has pytype farm its pytype-single calls out to ninja via subprocess. At the end
of the change description, I've included a short explanation of how ninja works;
for more detail, there's https://ninja-build.org/manual.html.
I've called this change "naive" because it does not:
(1) avoid clearing pytype_output/ so that output can be reused between runs or
(2) generate fine-grained dependency info so that ninja can parallelize builds.
These improvements will be in future CLs.
Makes progress toward #173. Fixes #169.
* Adds this change to a new CHANGELOG file. We discussed starting a changelog
in the meeting, so we might as well start now. I've added a single entry for
the most recent release, to show how the file will be structured; I'll
backfill the rest of the file later.
* Adds ninja to …
=> Have pytype (naively) generate ninja files.

setup.py
Updates the URL that PyPI uses for the "Homepage" link on the left of the project page
(https://pypi.org/project/pytype/).
=> Update the PyPI url in setup.py

pytype/tests/py2/test_stdlib.py, pytype/tests/py3/test_stdlib.py, pytype/tests/test_stdlib.py
I've also copied over a test fix. From past experience, this shouldn't confuse copybara too much, although it'll probably generate an empty commit.
=> Update the typeshed pin to match the internal version.

setup.py
Named the binary `pyxref` (thanks to @kamahen  for the suggestion)
=> add an executable for xref to setup.py

setup.py
PyPI doesn't seem to recognize Stable, and a classifer search shows
projects using Production/Stable.
=> Change our development status from Stable to Production/Stable.

setup.py
In lower versions, this requirement causes an installation failure:
https://travis-ci.org/google/python-fire/jobs/514951139.
=> Only require typed_ast in 3.3+.

CHANGELOG, pytype/__version__.py
=> Bump pytype's PyPI version number for a release.

.travis.yml, build_scripts/py27.py, build_scripts/pyexe.py, build_scripts/run_cc_test.py, build_scripts/run_tests.py, build_scripts/travis_script.py, pylintrc, setup.py
* Lints the rest of our source files not in pytype/.
* Edits those files to be free of lint errors, disables relative-import
because it only fires in 2.7 and doesn't seem to be useful.
* Tweaks pylintrc to be a little easier to read and maintain.
* Moves the pylint step from .travis.yml to build_scripts/travis_script,
alphabetizes installs in .travis.yml.
=> Run pylint over build_scripts/ and setup.py as well.

CHANGELOG, pytype/__version__.py, pytype/load_pytd.py, pytype/pytd/serialize_ast.py, pytype/pytd/serialize_ast_test.py, pytype/pytd/typeshed.py, pytype/pytd/typeshed_test.py, pytype/pytd/visitors.py, pytype/pytd/visitors_test.py, pytype/tests/test_import.py, pytype/tests/test_pickle.py, pytype/tools/xref/indexer.py
This is a problem when a pyi files does `from X import Y as Y` with
the intent to re-export Y. pytype would see Alias(Y, X.Y) and assume
that X was a module and Y a module attribute. Instead, we need to
detect when X is a package and attempt to load a pyi for X.Y.
When this is LGTM'd, I'll update __version__ and CHANGELOG with
the current date before submitting, so that I can do a PyPI release
and unblacklist the affected third_party typeshed files.
Makes progress toward https://github.com/google/pytype/issues/171.
PiperOrigin-RevId: 247335339
=> Fix a bug where pytype would fail to resolve an unused import.

pytype/mixin.py, pytype/tests/py2/test_classes.py, pytype/tests/py3/test_classes.py, pytype/tests/test_classes.py
Also updates `pytype/mixin.py` and some test cases to reflect that in py3,
`unittest.TestCase` is in `unittest/case.pyi` rather than `unittest/__init__.pyi`.
Fixes https://github.com/google/pytype/issues/150,
makes a lot of progress toward https://github.com/google/pytype/issues/171.
=> Update typeshed to 50d98acc766e9425cb099c17b711f1bccb697584.

pytype/pyc/pyc.py
Also manually copies a fix to keep pytype itself building.
=> Update typeshed to 40215d1fa3ef33a31fe68624472c10dd62350f18.

CHANGELOG, pytype/__version__.py, pytype/pyi/parser.yy, pytype/pyi/parser_test.py
Addresses failing pytype test in https://github.com/python/typeshed/pull/3149.
I'm planning to do a mini external release today for this fix, since the
internal release includes everything up to it, and the parser change has a very
low likelihood of breaking anything.
PiperOrigin-RevId: 260765164
=> Allow trailing commas in lists in type stubs.

setup.py
I also fixed the alphabetization of the scripts - `pytype-single` was in the wrong place.
=> Add an entrypoint for annotate-ast to setup.py.

build_scripts/release.py, setup.py
As it turns out, reStructuredText is not happy with unicode characters.
But since March 2018, PyPI has allowed using markdown for the long
description, which works: https://test.pypi.org/project/pytype/.
=> Use README.md for the PyPI description.

build_scripts/run_tests.py, build_scripts/travis_script.py, cmake/modules/PyTypeUtils.cmake
I poked around at this a bit more and discovered that excluding tests in Python 2 isn't as messy as I was afraid it would be, so we should just go ahead and do it so we can stop worrying about accidentally using py3-only features in xref. I also found what was likely a copy/paste error in the cmake file ('py_library' instead of 'py_test'), so I fixed that, too.
=> Don't lint or test xref in Python 2.

build_scripts/build_utils.py, build_scripts/run_tests.py, build_scripts/travis_script.py
Currently, when a test fails on Travis, we get no information except the
test name and a path to a log file we can't access. Instead, we should
print the log file to stderr.
=> Add a verbose mode to print failing test logs to stderr.

CHANGELOG, pytype/__version__.py
http://dashboards/pytype_status shows only a handful of failures, none of which
look like pytype bugs.
PiperOrigin-RevId: 266233511
=> Update pytype __version__ and CHANGELOG for a PyPI release.

.travis.yml
See https://github.com/google/pytype/issues/423.
=> Temporarily pin to an older version of pylint.

README.md, docs/index.md
ln 17 - don't need the meaning, if we just replace it with a semicolon it can be inferred that static analyzers dont execute the code it runs on
Resolves #431
PiperOrigin-RevId: 275130550
=> Documentation Edits wording/grammer/cleanup (#431)

pytype/pytd/optimize.py
The unnecessary comprehension was flagged by the most recent upstream release
of pylint.
For https://github.com/google/pytype/issues/423.
PiperOrigin-RevId: 285068776
=> Remove an unnecessary list comprehension.

pytype/tools/annotate_ast/main.py
These two modules were not declared as modules because their `__init__.py` is missing. Python 3+ compensates for this by considering them namespaces, but the `annotate-ast` command (and probably a few others) are broken on Python 2.7 due to lack of an `__init__.py`
Resolves #508
PiperOrigin-RevId: 293690334
=> Add __init__ files to two tools modules (#508)

pytype/convert.py, pytype/function.py, pytype/pyi/parser.py, pytype/pyi/parser_test.py, pytype/tests/py3/test_annotations.py, pytype/tests/py3/test_generic.py
=> Remove pytype's support for implicit None annotations.

pytype/pytd/builtins/3/__builtin__.pytd, pytype/pytd/builtins/3/builtins.pytd, pytype/tests/py3/test_builtins.py
Resolves https://github.com/google/pytype/issues/513.
PiperOrigin-RevId: 295241887
=> Allow a range to be sliced in Python 3.

pylintrc
The error is being reported here:
https://travis-ci.org/github/google/pytype/jobs/669392038. Looks like a
false positive to me.
=> Disable lint error not-an-iterable.

build_scripts/pyexe.py
With this fix, our Travis script will report type-checking failures.
=> Call sys.exit() with the return code in build_scripts/pyexe.

build_scripts/test_module.py
Classes should be skippable just like methods:
https://docs.python.org/3/library/unittest.html#skipping-tests-and-expected-failures.
Make this feature work with our unusual test setup.
=> Support skipping an entire TestCase.

CONTRIBUTING.md, requirements.txt
With this, we can run `pip install -r requirements.txt` to get all the
dependencies for building and testing the GitHub code locally.
Previously, I was looking at .travis.yml every time to figure out what
to install.
Based on
https://packaging.python.org/discussions/install-requires-vs-requirements/,
setup.py's install_requires and requirements.txt accomplish different
purposes, so I haven't tried to keep them in sync.
I'm also hoping that adding this file will fix our broken dependency
graph, which currently shows no dependencies and no dependents:
https://help.github.com/en/github/visualizing-repository-data-with-graphs/listing-the-packages-that-a-repository-depends-on.
I also deleted a stray newline in CONTRIBUTING.md, because why not?
=> Add a requirements.txt.

build_scripts/test_module.py
When __dict__ is used, subclasses don't pick up inherited test methods.
Since TargetIndependentTest subclasses test classes to add Python 2
testing, this bug meant that there were a whole bunch of 2and3 tests
that we were running in Python 3 only.
=> Use dir() instead of __dict__ to find test methods.

.gitignore
Currently installing the project locally with pip causes the following files to be retained in the git tree:
```
build/
build_scripts/__pycache__/
build_scripts/build_utils.pyc
build_scripts/py27.pyc
pip-wheel-metadata/
pytype.egg-info/
pytype/__pycache__/
pytype/pyc/__pycache__/
pytype/pyi/parser_ext.cpython-37m-x86_64-linux-gnu.so
pytype/pytd/__pycache__/
pytype/pytd/parse/__pycache__/
pytype/typegraph/__pycache__/
```
This just adds the standard [Github `.gitignore` for Python](https://github.com/github/gitignore/blob/master/Python.gitignore) into the repo and gets rid of these.
=> Add a top-level .gitignore

CHANGELOG, pytype/__version__.py
The new version of pytype looks good (I'm just waiting for a few more Rosie CLs
to be submitted before releasing it internally), so we can go ahead with the
PyPI release.
PiperOrigin-RevId: 311404665
=> Prepare for a PyPI release.

CHANGELOG, pytype/__version__.py
=> Update __version__ and CHANGELOG for a PyPI release.

.github/workflows/build.yml
Building of the manylinux wheel started failing consistently five days ago: https://github.com/google/pytype/actions/runs/170384447. As far as I can tell, what happened is that the ubuntu-latest image was updated to a version in which the docker command-line tool is provided by the moby-cli and moby-engine packages and does not need to be separately installed. (In fact, installing `docker` causes the previous two packages to be uninstalled.)
The MacOS wheels are also failing, but those failures are due to timeouts and the builds intermittently succeed, so I *think* that one's not our fault.
=> Remove no-longer-necessary docker installation step.

pytype/imports_map_loader_test.py
Fixes https://github.com/google/pytype/issues/629.
PiperOrigin-RevId: 323855323
=> Make imports_map_loader_test work with custom $TMPDIR values.

CHANGELOG, pytype/__version__.py
For yet another pyi parser fix (https://github.com/google/pytype/issues/626).
PiperOrigin-RevId: 324104646
=> Do a PyPI release.

CHANGELOG, pytype/pyi/lexer.lex, pytype/pyi/lexer_test.py, pytype/pyi/parser.h, pytype/pyi/parser.py, pytype/pyi/parser.yy, pytype/pyi/parser_ext.cc, pytype/pyi/parser_test.py, pytype/tests/py3/test_typing.py
Since we don't support TypedDict yet, the parser simply rewrites TypedDict
to Dict[str, Any].
Fixes https://github.com/google/pytype/issues/637.
PiperOrigin-RevId: 327131566
=> Support TypedDict function-based syntax in pyi files.

build_scripts/release.py, pylintrc
Disable three new errors. c-extension-no-member doesn't seem useful;
super-with-arguments and raise-missing-from we're not ready for because
they assume Python 3-only.
build_scripts/ *is* py3-only, so I fixed an instance of
super-with-arguments there.
For https://github.com/google/pytype/issues/656.
=> Clean up some lint errors.

pylintrc
Fixes https://github.com/google/pytype/issues/656.
=> Re-enable Python 3-only lint errors.

.github/workflows/build.yml, .travis.yml, pylintrc, setup.cfg
Python 3.9 is "3.9-dev" on Travis:
https://travis-ci.community/t/python-3-9-support/6703.
The m flag for manylinux Python tags is dropped in 3.8:
https://github.com/pypa/manylinux/blob/master/README.rst#manylinux2014.
Since it was trivial to do, I also silenced an incorrect lint error that
shows up in 3.9:
"Value 'Union' is unsubscriptable (unsubscriptable-object)"
(or sometimes 'Optional').
For https://github.com/google/pytype/issues/440.
=> Declare Python 3.8 support (whoo!) and add 3.9 to the testing matrix.

cmake/modules/PyTypeUtils.cmake
typegraph.metrics has no srcs, which made CMake unhappy. Removes the
requirement that srcs be non-empty, and specify the linker language,
since CMake can't figure it out automatically when there are no .cc
files.
=> Fix CMake error triggered by a cc_library with no srcs.

build_scripts/build_utils.py, build_scripts/run_tests.py
We already print out test failures, but build failures that cause a test
to fail without even generating a log still lead to terse, uninformative
logs. Remedy this by printing out the relevant lines of ninja.log.
=> Improve the Travis logs for ninja build failures.

.travis.yml
My previous cmake change worked fine locally but failed on Travis once I
tried to pull in a no-srcs cc_library. Turns out that the cmake version
in most of Travis's build environments is quite old, but Focal Fossa is
nice and modern (so modern that we don't need to separately install
Python 3.6 and 3.7 but do need to install 2.7!).
=> Switch the Travis build environment to Focal Fossa.

setup.cfg
pytype requires this version of ninja as of a couple weeks ago, but I
forgot to include the version requirement in setup.cfg, with the result
that users can end up in a broken state if they install pytype in an
environment that already has an older ninja version installed.
For https://github.com/google/pytype/issues/685.
=> Require ninja 1.10.0.post2.

pytype/pytd/visitors.py, pytype/typegraph/cfg_utils.py
This PR changes the visitor and typegraph utils to use list comprehensions for flattening nested sequences instead of `sum([...], [])` which can be slow for large inputs. This should improve readability and also slightly improve performance.
Resolves #693
PiperOrigin-RevId: 335062627
=> Use list comprehensions for flattening (#693)

Dockerfile.dev
The Dockerfile includes all the dependencies needed to make pytype run in Docker and hopefully makes contributing easier for some.
=> Add Dockerfile for development

CONTRIBUTING.md
It comes obvious when building pytype that these are required but was never mentioned in the CONTRIBUTING guide.
=> Mention requirements.txt in CONTRUBUTING guide

build_scripts/wheels/manylinux.sh
manylinux wheel build is failing with
ln: failed to create symbolic link ‘/usr/local/bin/cmake’: File exists
I figured this out by going to Settings > Secrets and adding an "ACTIONS_STEP_DEBUG" secret with value "true", which gave us more verbose logs that included the above failure line.
=> Stop manually downloading cmake to fix manylinux wheel build.

.github/workflows/build.yml
Our latest Build Wheels run included a deprecation warning:
https://github.com/google/pytype/actions/runs/296426515.
The non-deprecated way to set an environment variable is:
https://docs.github.com/en/free-pro-team@latest/actions/reference/workflow-commands-for-github-actions#setting-an-environment-variable.
=> Migrate away from set-env.

.github/workflows/build.yml, .travis.yml, build_scripts/wheels/manylinux.sh, setup.cfg
Python 3.5 has reached end-of-life; dropping support for host 3.5 allows us to use shiny new 3.6 features in our code.
I noticed that I had accidentally left an unused CMAKE_VERSION variable in a wheel script in a previous PR, so I took the opportunity to delete it.
=> Drop support for running pytype under Python 3.5.

.travis.yml
this PR intends to: 
1. update the `.travis.yml` file to specify `python` versions under `python` to simplify the `include` section.
2. update the `install` to use `requirements.txt` instead of installing the packages individually and make `.travis.yml` more readable
=> updated the travis configuration to simplify dependencies

.gitmodules, pytype/CMakeLists.txt, requirements.txt, setup.py
- adds pybind11 as a submodule.
- disables cfg.py and builds cfg.so instead.
=> Prepare to use pybind11.

.gitmodules
This is necessary in order to use pybind11's CMake rules.
=> Add pybind11 as a submodule.

MANIFEST.in, pyproject.toml, requirements.txt, setup.py
This is a suggestion for using pybind11 via submodule. pyproject.toml is more elegant, but does require Pip 10+. I can switch to that if requested. Follow up on #714. I don't know all the details of building from scratch (It wants bison 3), but this should be close, I think. CC @rwgk .
I did not include ParallelCompile, but that might also be useful, I think.
=> fix: simplifiy pybind11 usage

build_scripts/wheels/macos.sh
Our build wheels workflow started failing again. I found a workaround in https://github.com/actions/virtual-environments/issues/1811. I suspect that at some point the workflow will fail again, and we'll have to remove the "brew untap" lines =P
=> Fix the Build MacOS wheels actions.

MANIFEST.in, setup.py
I was getting errors about cfg_logging.h being missing when trying to
test a new release; this change seems to fix the issue.
I'm still seeing some odd dynamic import failure, but python3.7 on my
machine also appears to be half-broken right now, so I have no idea if
the issue is with the pytype code or my environment.
=> Fix pip install errors.

.github/workflows/build.yml, .github/workflows/ci.yml, build_scripts/ci_script.py
Follow-up to https://github.com/google/pytype/pull/743:
* Renames travis_script to ci_script, now that we're no longer using Travis.
* Makes sure both workflows run on PRs and don't run unnecessarily on pushes to non-master branches. Also adds a workflow_dispatch trigger so they can be manually run.
=> Improve GitHub Actions workflows.

CONTRIBUTING.md
Adds:
* A command for pip-installing from source.
* A link to the dev guide.
* A command for also running pylint and pytype over the pytype source,
in addition to running the tests.
For https://github.com/google/pytype/issues/570.
=> Add more information to CONTRIBUTING.md.

build_scripts/wheels/macos.sh
Homebrew was recently updated
(https://github.com/actions/virtual-environments/issues/2415),
introducing a bug related to 2to3:
https://github.com/actions/virtual-environments/issues/2428. I applied
the workaround recommended in the issue.
=> Fix MacOS wheel builds.

pytype/pyi/typed_ast/ast_parser.py, pytype/pyi/typed_ast/ast_parser_test.py, pytype/pyi/typed_ast/classdef.py, pytype/pyi/typed_ast/conditions.py, pytype/pyi/typed_ast/definitions.py, pytype/pyi/typed_ast/function.py, pytype/pyi/typed_ast/modules.py, pytype/pyi/typed_ast/namedtuple.py, pytype/pyi/typed_ast/parse_ast.py, pytype/pyi/typed_ast/types.py, pytype/pyi/typed_ast/typeshed_parsing_test.py, pytype/pyi/typed_ast/visitor.py, setup.cfg
This parser is intended as a drop-in replacement for the current yacc-based
parser. Rather than maintaining our own grammar, it uses the standard typed-ast
library to parse pyi files as python3 code, before converting them to pytype's
internal data structures. This fixes several issues with pytype not parsing
some constructs in typeshed, and should help us track future python syntax
changes a lot more easily.
Since this has several conflicts with the existing parser, it has been
developed internally in a separate branch, and is being merged in as a unit. We
will add detailed documentation of its internals to our developer docs.
PiperOrigin-RevId: 352670366
=> Export the typed_ast pyi parser to github.

CHANGELOG, pytype/__version__.py
The Build Failures table looks good, so here we go...
PiperOrigin-RevId: 353069312
=> Do a PyPI release of the new pyi parser.

setup.cfg
For https://github.com/google/pytype/issues/749.
I manually ran the pytype tests with host version = 3.9 and target = 3.8
to confirm that, while pytype cannot yet analyze 3.9 code, it has no
trouble running under 3.9.
This change
(1) Ensures that users attempting to install pytype in 3.9 get the
latest version. Currently, they get version 2020.2.6, which is old and a
little broken (see, e.g., https://github.com/google/pytype/issues/834).
(2) Allows users to run pytype in 3.9 and analyze 3.5-3.8 code by
specifying --python_version. This is arguably not very useful, since
pytype won't be able to resolve pip-installed dependencies, but it may
be good enough for small, self-contained projects.
Attempting to run pytype in 3.9 without specifying a lower target version will still produce a …
=> Allow pytype to be installed in Python 3.9.

pytype/abstract.py, pytype/abstract_utils.py, pytype/matcher.py, pytype/tests/py3/test_protocols.py
Previously, pytype only took methods into account for protocol matching. But if
a class has a constant whose type has a `__call__` method, that constant should
be allowed to satisfy a method in a protocol.
Fixes https://github.com/google/pytype/issues/753.
PiperOrigin-RevId: 359181707
=> Allow callable constants to match protocol methods.

pytype/abstract.py, pytype/tests/py3/test_tuple.py, pytype/tests/test_errors.py, pytype/tests/test_tuple.py
Fixes https://github.com/google/pytype/issues/839.
PiperOrigin-RevId: 359212099
=> Allow builtins.tuple to be used for a heterogeneous tuple annotation.

CHANGELOG, pytype/__version__.py
I also modified the CHANGELOG entry from 2021.02.23 because I realized I forgot
to include the typeshed update ^^;
PiperOrigin-RevId: 360752807
=> Prepare a PyPI release.

.github/workflows/ci.yml
👋 hello there! I'm a fellow Googler who works on projects that leverage GitHub Actions for CI/CD. Recently I noticed a large increase in our queue time, and I've tracked it down to the [limit of 180 concurrent jobs](https://docs.github.com/en/actions/reference/usage-limits-billing-and-administration) for an organization. To help be better citizens, I'm proposing changes across a few repositories that will reduce GitHub Actions hours and consumption. I hope these changes are reasonable and I'm happy to talk through them in more detail.
- **(you were already doing this, thank you!)** Only run GitHub Actions for pushes and PRs against the main branch of the repository. If your team uses a forking model, this change will not affect you. If your team pushes branches to the repository directly, …
=> Improve Actions hygiene

docs/user_guide.md
Not sure what the meaning of /2 is, but clicking the link yields GitHub's 404. Removing it points to valid examples to `.pyi` files.
=> Fix dead pyi-examples link in user_guide.md

pylintrc
This warning (new in the 3.9 tests) does not seem useful.
=> Ignore pylint warning.

pytype/load_pytd_test.py, pytype/pyi/definitions.py, pytype/pyi/parser.py, pytype/pyi/parser_test.py, pytype/pytd/printer.py, pytype/pytd/visitors_test.py
pytype will gracefully fall back to Any when typing.ParamSpec or
typing.Concatenate is used as the first argument to a Callable in a type stub,
allowing typeshed to start using most of PEP 612. Custom generic classes
parameterized with a ParamSpec are still not supported.
pytype was reporting weird [bad-unpacking] errors in parser.py, so I kept
adding ast3.AST annotations until they went away.
I also fixed a bug in PrintVisitor that caused it to print typing_extensions
imports as aliases rather than imports.
For https://github.com/google/pytype/issues/786.
PiperOrigin-RevId: 366342708
=> Add some minimal support for PEP 612 in type stubs.

pylintrc
This warning seems useful, so I may reenable it later, but the changes
needed to satisfy it are not obviously safe, so disabling for now.
=> Disable lint warning consider-using-with.

pytype/abstract.py, pytype/abstract_utils.py, pytype/annotations_util.py, pytype/function.py, pytype/overlays/attr_overlay.py, pytype/overlays/classgen.py, pytype/overlays/dataclass_overlay.py, pytype/state.py, pytype/vm.py
I'm trying to add support to pytype for annotating a class's attributes with
TypeVars that the class is generic in, which should also partially fix the
generic containers bug. As usual, the change got much too large, so this is the
part of it that shouldn't have any user-visible effect.
* Pulls out various pieces of code in abstract.py into their own methods, so
they can be later extended and/or reused.
* Moves InterpreterFunction._mutations_generator into the SignedFunction base
class, so it can also be used in SimpleFunction. (Amazingly,
_mutations_generator works with no changes on SimpleFunctions!)
* Replaces the is_var argument to extract_annotation() with
allowed_type_params, which tells pytype what type parameters are in scope and
are allowed to be used in annotations. …
=> Do some cleanup/refactoring to prepare for a generics bug fix.

pytype/pyi/parser.py, pytype/pyi/parser_test.py
Part of #785, though not a complete fix because this doesn't allow the `|` syntax at runtime (I think).
Resolves #924
PiperOrigin-RevId: 374269437
=> Add support for PEP 604 (Union |) in stub files (#924)

pytype_extensions/LICENSE, pytype_extensions/README.md, pytype_extensions/__init__.py, pytype_extensions/test_pytype_extensions.py
This exports pytype_extensions as a new directory in the pytype GitHub repo.
The config is branched from pytype/copy.bara.sky.
PiperOrigin-RevId: 377313194
=> Add an initial copybara config for pytype_extensions.

pylintrc, pytype/io.py, pytype/io_test.py, pytype/pytd/typeshed.py, pytype/tools/analyze_project/config_test.py, pytype/typegraph/cfg_test.py
typeshed/tests/pytype_test was still broken for third-party stubs. This turned
out to be because, even ignoring @python2, a package can contain multiple
modules, and a module name can be provided by multiple packages. I also noticed
that typeshed seems to have added a @tests directory; accidentally including it
as a module name doesn't hurt but is technically wrong, so I filtered it out.
PiperOrigin-RevId: 392084509
=> Fix typeshed _load_third_party_packages().

.github/workflows/ci.yml, requirements.txt, setup.cfg, setup.py
For https://github.com/google/pytype/issues/1044.
See https://github.com/google/pytype/issues/1047 for an explanation of the weirdness going on with astroid/pylint.
I also fixed a lint issue in setup.py that I noticed while playing around with installing various versions of pylint.
=> Update typed-ast to 1.5.0, which contains a Python 3.9.8 fix.

pytype/tools/annotate_ast/main.py, pytype/tools/xref/indexer.py, requirements.txt, setup.cfg
Since 2a6a1cebb13a71d5a2dda08ef2e260a81659b392 `pytype` will use the builtin `ast` module instead of `typed-ast` for Python 3.8 or newer. This PR removes the dependency from the requirements files for these newer Python versions.
=> Only require `typed-ast` for Python < 3.8

CHANGELOG, pytype/__version__.py, pytype/tools/analyze_project/config.py, pytype/tools/analyze_project/pytype_runner.py, pytype/tools/analyze_project/pytype_runner_test.py
Previously, feature flags were passed only to CHECK, so flags that modify
inference behavior didn't work.
Also bumps __version__ and CHANGELOG so I can release this immediately. (No
point in waiting for nightly testing, since we don't use analyze_project
internally anyway.)
For https://github.com/google/pytype/issues/1057.
PiperOrigin-RevId: 412996772
=> analyze_project: pass feature flags to the INFER command.

setup.cfg
The type errors in these files were fixed a few weeks ago.
=> Stop excluding pytype/pyi/ files from type-check.

pytype/convert.py, pytype/tests/test_typing2.py
Fixes https://github.com/google/pytype/issues/1138.
PiperOrigin-RevId: 431027196
=> Unpack ClassVar in constant_to_var so unions are handled correctly.

CONTRIBUTING.md, cmake/modules/PyTypeUtils.cmake, requirements.txt
Noticed these issues while setting up a pytype dev environment on a new machine.
* Remove code that checked for the presence of bison and flex, which
haven't been needed for a while.
* Note in CONTRIBUTING.md that the python3.x-dev package is also needed;
I got a cryptic error from pybind11 when it was missing.
* Remove a line from requirements.txt that was previously needed to
force installation of a newer version of astroid than pylint required.
=> Clean up pytype install requirements and documentation.

pytype/ast/visitor.py, pytype/directors/CMakeLists.txt, pytype/directors/directors.py, pytype/directors/directors_test.py, pytype/directors/parser.py, pytype/directors/parser_libcst.py, pytype/io.py, pytype/pyi/visitor.py, pytype/tests/test_type_comments1.py
The ast library is much faster.
We still need libcst for 3.8 and earlier, since we're making use of recent ast
features like the 'end_lineno' attribute on nodes.
PiperOrigin-RevId: 456423980
=> Replace libcst with ast in directors.py in Python 3.9+.

pytype/directors/directors.py
Return statements are always regular line ranges, not call ranges.
PiperOrigin-RevId: 456615690
=> Don't use Call line ranges to move function range end lines.

.github/workflows/ci-windows.yml, .github/workflows/ci.yml, pytype/abstract/abstract_utils.py, pytype/context.py, pytype/directors/parser.py, pytype/directors/parser_libcst.py, pytype/vm_utils.py
* Reorganize abstract_utils.py so that public classes and the special
_isinstance and _make methods are at the top of the file.
* Use abstract.Class, not class_mixin.Class, to refer to Class in context.py.
* Make parser.BlockReturns private.
* Fix another 3.11 lint warning (missing super call) in vm_utils.py.
PiperOrigin-RevId: 461989284
=> Fix a few very minor style issues.

.pre-commit-hooks.yaml
Closes #1300. Allows running pytype as a pre-commit hook. The caveat is, pytype still needs to be installed in the virtual environment where the type checks are being performed.
To test this from your python project:
```bash
pip install pre-commit pytype
pre-commit try-repo --verbose --all-files https://github.com/ilCatania/pytype.git
```
and you should get an output similar to this:
```
[INFO] Initializing environment for https://github.com/ilCatania/pytype.git.
===============================================================================
Using config:
===============================================================================
repos:
-   repo: https://github.com/ilCatania/pytype.git
rev: 5a1228e8b277c3446c50fdc3767bd5057a886405
hooks:
-   id: pytype …
```
=> add pre-commit hook definition

setup.cfg
The same information is in pyproject.toml, which is supported as of version 2023.01.10.
=> Remove [pytype] section from setup.cfg.

pytype/pyi/parser.py, pytype/pyi/parser_test.py
See python/typeshed#9501.
Resolves #1350
PiperOrigin-RevId: 501717379
=> Do not parse default values as types (#1350)

setup.cfg
This prevents installation of very old versions of pytype when a newer version than supported is requested. Instead, the latest version of pytype will be installed, and it'll fail with a sensible error message about 3.xx not being supported yet.
Fixes https://github.com/google/pytype/issues/1481.
=> Remove max Python version requirement from setup.cfg.

docs/support.md, pytype/abstract/_classes.py, pytype/annotation_utils.py, pytype/attribute.py, pytype/overlays/fiddle_overlay.py, pytype/pytd/visitors.py, pytype/tests/test_typing_self.py
For #1283.
PiperOrigin-RevId: 576676199
=> typing.Self: support Self in variable annotations.

pytype/output.py, pytype/overlays/CMakeLists.txt, pytype/overlays/overlay_utils.py, pytype/overlays/typed_dict.py, pytype/overlays/typing_overlay.py, pytype/tests/test_typed_dict.py
Fixes https://github.com/google/pytype/issues/1551.
PiperOrigin-RevId: 592386426
=> Support typing.Required and typing.NotRequired.

pytype/pytd/visitors.py
This fixes a failure in typeshed's pytype_test.
PiperOrigin-RevId: 605760245
=> Ignore non-aliased module nodes when collecting dependencies.

pytype/tools/analyze_project/pytype_runner.py, pytype/tools/analyze_project/pytype_runner_test.py
This fixes https://github.com/google/pytype/issues/499
Unfortunately, I was not able to get pytype running on my machine, so this commit is just based on what seems like the right idea to me, and hopefully it can be verified to be correct by a maintainer and then merged.
=> Update pytype_runner.py - change escape_ninja_path to escape all the ninja path escape-needing characters
